title: Patterns
author: Cornelis G. A. Kolbach
#baseurl: http://syslab.com
domain: syslab.com
media: /media
markdown: kramdown
permalink: /:title/
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
defaults:
-
  scope:
    path: _posts/en
  values:
    layout: default
    lang: en
-
  scope:
    path: _posts/de
  values:
    layout: default
    lang: de

t:
  en:
    home: "Home"
    andother: "and powerful"
    createdby: "created by"
    social_intranet_solutions: "Social intranet solutions"
    social_intranet_solutions_text: "Quaive Intranet connects the people in your organisation and helps them to stay focussed."
    risk_assessment_tools: "Risk Assessment Solutions"
    web_solutions: "Web solutions"
    references_text: "We shape the web for a wide variety of businesses and organisations."
    people_headline: "People"
    people_byline: "The people behind Syslab.com"
    people_subline: "…plus a team of highly skilled and open-source devoted developers, designers and administrators."
    team: "The team"
    careers: "Careers"
    careers_you: "You?"
    careers_you_text: "Would you like to work with these highly skilled people? Please have a look at our vacancies…"

  de:
    home: "Start"
    andother: "und leistungsfähige"
    createdby: "entwickelt von"
    social_intranet_solutions: "Social Intranet Lösungen"
    social_intranet_solutions_text: "Quaive Intranet verbindet die Menschen und hilft ihnen, zu fokussieren."
    risk_assessment_tools: "Gefährdungsbeurteilungtools"
    web_solutions: "Weblösungen"
    references_text: "Wir formen das Web für Firmen und Organisationen."
    people_headline: "Mitarbeiter"
    people_byline: "Die Menschen hinter Syslab.com"
    people_subline: "…sowie ein Team aus hochspezialisierten Open-Source Entwicklern, Designern und Administratoren."
    team: "Unser Team"
    careers: "Karriere"
    careers_you: "Du?"
    careers_you_text: "Reizt es dich, mit hochqualifizierten Menschen zu arbeiten? Wirf einen Blick auf unsere offenen Stellen…"

mainnav:
  en:
    homepage:
      name: "Homepage"
      url: "/homepage/index.html"
    socialintranet:
      name: "Social intranet"
      url: "/homepage/index.html#intranet-solutions"
    riskassessmenttools:
      name: "Risk Assessment Tools"
      url: "/homepage/index.html#risk-assessment-tools"
    websolutions:
      name: "Web solutions"
      url: "/homepage/index.html#services"
    people:
      name: "Passionate Teams"
      url: "/homepage/index.html#people"
  de:
    homepage:
      name: "Startseite"
      url: "/startseite/index.html"
    socialintranet:
      name: "Social Intranet"
      url: "/startseite/index.html#intranet-solutions"
    riskassessmenttools:
      name: "Gefährdungsbeurteilungtools"
      url: "/homepage/index.html#risk-assessment-tools"
    websolutions:
      name: "Weblösungen"
      url: "/startseite/index.html#services"
    people:
      name: "engagierten Teams"
      url: "/startseite/index.html#people"

appendix:
  en:
    contact:
      name: "Contact"
      url: "/contact/"
    about:
      name: "About"
      url: "/about/"
    press:
      name: "Press"
      url: "/press/"
    disclaimer:
      name: "Disclaimer"
      url: "/disclaimer/"
    news:
      name: "News"
      url: "/homepage/index.html#news"
    careers:
      name: "Careers"
      url: "/homepage/index.html#careers"
  de:
    contact:
      name: "Kontakt"
      url: "/kontakt/"
    about:
      name: "Über"
      url: "/ueber/"
    press:
      name: "Presse"
      url: "/presse/"
    disclaimer:
      name: "Haftungsausschluss"
      url: "/haftungsausschluss/"
    news:
      name: "News"
      url: "/startseite/index.html#news"
    careers:
      name: "Karriere"
      url: "/homepage/index.html#careers"
