title: Patterns
author: Cornelis G. A. Kolbach
#baseurl: http://syslab.com
domain: syslab.com
media: /media
markdown: kramdown
permalink: /:title/
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
defaults:
-
  scope:
    path: _posts/en
  values:
    layout: default
    lang: en
-
  scope:
    path: _posts/de
  values:
    layout: default
    lang: de
